[project]
name = "task-cv-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam Aly", email = "adamaly243@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
]

[project.scripts]
task-cv-1 = "task_cv_1:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
