[project]
name = "task-vehicle-speed-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Adam Aly", email = "adamaly243@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "ultralytics>=8.4.163",
]

[project.scripts]
task-vehicle-speed-detection = "task_vehicle_speed_detection:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
